apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinosaur
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dinosaur
  template:
    metadata:
      labels:
        app: dinosaur
    spec:
      containers:
        - name: dinosaur
          image: IMAGE
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
          envFrom:
            - configMapRef:
                name: dinosaur